import { supabase } from '../lib/supabase';

export async function createCouple(userId) {
  // 1. Create couple row (invite_code auto-generated by DB)
  const { data: couple, error: coupleErr } = await supabase
    .from('couples')
    .insert({})
    .select()
    .single();
  if (coupleErr) throw coupleErr;

  // 2. Add current user as member
  const { error: memberErr } = await supabase
    .from('couple_members')
    .insert({ user_id: userId, couple_id: couple.id });
  if (memberErr) throw memberErr;

  return couple;
}

export async function joinCouple(userId, inviteCode) {
  // 1. Find couple by invite code
  const { data: couple, error: findErr } = await supabase
    .from('couples')
    .select('id')
    .eq('invite_code', inviteCode.trim().toLowerCase())
    .single();
  if (findErr || !couple) throw new Error('Kode undangan tidak ditemukan');

  // 2. Check couple isn't full (max 2 members)
  const { count } = await supabase
    .from('couple_members')
    .select('*', { count: 'exact', head: true })
    .eq('couple_id', couple.id);
  if (count >= 2) throw new Error('Pasangan ini sudah penuh (maks 2 orang)');

  // 3. Add user as member
  const { error: joinErr } = await supabase
    .from('couple_members')
    .insert({ user_id: userId, couple_id: couple.id });
  if (joinErr) throw joinErr;

  return couple;
}
